### ISSUE TITLE
Berlin-Wedding incorrectly translated

### ISSUE THREAD

**Issue by RealDolos** [whosonfirst-data/whosonfirst-data-admin-de#27]
https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/420/784/285/420784285.geojson

Berlin-Wedding lists:
```json
    "name:deu_x_preferred":[
        "Hochzeitsfeier"
    ],
    "name:deu_x_variant":[
        "Wedding",
        "Berlin-Wedding"
    ],
```

`name:deu_x_preferred` is what you get when you put Wedding into google translate. It is wrong. The German for Berlin "Wedding" is "Wedding", i.e. it already is the German name and does not need a translation, it's not about people getting married at all (it was named after Rudolf de Weddinge according to wikipedia).

it looks like most/all the other `_x_preferred`s are wrongly translated as well.
E.g.
```json
    "name:cym_x_preferred":[
        "Seremoni briodas"
    ],
```
No, Wedding is not a "bridal ceremony" 😉 .

I have no idea how exactly this is curated or where the problematic translation comes from, thus I am not making a PR, just reporting this as an issue.

I'd guess other places would be affected by such mistaken translations as well...

**Comment by stepps00** [comment]
Hi @RealDolos! Thanks for filing this issue.. I'm going to move this into the main `whosonfirst-data` repo as we try to use that repo to track all issues.

This is likely caused by our name work we've done through concordances and matching to Wikipedia and Wikidata. Rather than obtain new names for the "Hochzeitsfeier" name, we've incorrectly added names for the "Wedding" (ceremony) name. Nice catch!
